# Generated by Django 5.0.7 on 2024-08-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0002_remove_question_grade_subject_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultOfQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Student Name')),
                ('correct', models.CharField(max_length=30)),
                ('wrong', models.CharField(max_length=15)),
                ('emty', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('bad', 'bad'), ('poor', 'poor'), ('good', 'good'), ('better', 'better'), ('perfect', 'perfect')], max_length=20)),
                ('wrong_questions', models.JSONField(blank=True, default=list)),
                ('correct_questions', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
